version: '3.8'
services:
  penelope:
    build:
      context: ../
      dockerfile: ./docker/penelope/Dockerfile
    ports:
      - 8080:8080
    networks:
      - penelope_net
    depends_on:
      - db
    volumes:
      - /var/penelope_storage:/var/penelope_storage
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=penelope
      - POSTGRES_PASSWORD=longboi
      - POSTGRES_DB=cbg
    volumes:
      - /var/penelope_data:/var/lib/postgres/data
    networks:
      - penelope_net
networks:
  penelope_net: